on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24.1'
          elixir-version: '1.12'
      - uses: kvrhdn/gha-buildevents@v1
        with:
          # Required: a Honeycomb API key - needed to send traces.
          apikey: ${{ secrets.HC_APIKEY}}

          # Required: the Honeycomb dataset to send traces to.
          dataset: gha-buildevents_integration

          # Required: the job status, this will be used in the post section and sent
          # as status of the trace. Must always be ${{ job.status }}.
          job-status: ${{ job.status }}
      - run: |
          echo "STEP_ID=0" >> $GITHUB_ENV
          echo "STEP_START=$(date +%s)" >> $GITHUB_ENV
      - run: buildevents cmd $TRACE_ID $STEP_ID "dependencies" -- mix deps.get 
      - run: buildevents step $TRACE_ID $STEP_ID $STEP_START 'dependencies'
      - run: |
          echo "STEP_ID=1" >> $GITHUB_ENV
      - run: buildevents cmd $TRACE_ID $STEP_ID "tests" -- mix test 
      - run: buildevents step $TRACE_ID $STEP_ID $STEP_START 'tests'
